baseURL = "/"
title = "How Flutter"

# Language settings
defaultContentLanguage = "zh"

[[module.imports]]
    path = "github.com/google/docsy"


[languages]
[languages.zh]
contentDir = "content/zh"
languageName = "中文"
weight = 1

[menus]
[[menus.main]]
    identifier = "learn"
    pageRef = "/learn"
    